### ISSUE TITLE
Easymotion about chinese characters

### ISSUE THREAD

**Issue by whcn** [weakish/migemo-dict-zh#1]
你好，我想问下你知道如何把这个和easymotion结合在一起用吗？
我根据下面链接的第一个回复将utf8.vim里的内容替换成这个文件里的内容之后还是无法使用
https://github.com/easymotion/vim-easymotion/issues/145
想请教一下你是如何替换的？

**Comment by weakish** [comment]
> 你知道如何把这个和easymotion结合在一起用吗

不知道。时间比较久了，我记忆也比较模糊。记得当初并没有和easymotion结合，因为当初我并不会vimL。现在，我已经不怎么用vim了（主力是JetBrain全家桶和vscode的vim模式）。
